package org.omg.PortableServer;


/**
* org/omg/PortableServer/SERVANT_RETENTION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u421/1068/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, June 5, 2024 1:01:57 PM UTC
*/

public interface SERVANT_RETENTION_POLICY_ID
{

  /**
	 * The value representing SERVANT_RETENTION_POLICY_ID.
	 */
  public static final int value = (int)(21L);
}
